### ISSUE TITLE
Read WSI from Orthanc Server

### ISSUE THREAD

**Issue by selko** [ImagingDataCommons/slim#137]
Is it possible to run Slim and conmect to Orthanc to open whole slide images?

**Comment by hackermd** [comment]
Yes, that should be possible. We primarily use DCM4CHE, but we have tested the viewer with Orthanc a while back and others appear to successfully use it (see #82).

**Comment by hackermd** [comment]
Please feel free to open a separate in case you run into issues with using Orthanc.
