### ISSUE TITLE
Help with Slim / difference with Ohif

### ISSUE THREAD

**Issue by selko** [ImagingDataCommons/slim#138]
Hi all,

I tested OHIF and dicom-microscopy extension but i found this repo and it seems to be more updated. 
i wanted to know how can i start to develop new functionalities in this repo and if is there a O.S. preferred (ubuntu, debian, windows..)

in OHIF for example, i dont know how to work with openlayers because it loads a build version, and here it seems to be all separated.  I like OHIF  because it seems to be all kind of different dicom images more integrated,
but i don't know how load openlayers source.

Anyways, for me would be nice to start developing new functionalities over Slim. 
Some helpful would be apreciated.

i was developing for 7 years over OpenSeadragon and openslide and i would like to contribute in this line. 

Thank you in advance.

**Comment by pieper** [comment]
Thanks for your interest in Slim and OHIF 👍 .  For the Imaging Data Commons we have standardized on Slim for our microscopy interface and OHIF for radiology, so at least for IDC we are not using the dicom-microscopy extension in OHIF.  [The Slim paper](https://arxiv.org/pdf/2205.09122.pdf) provides more details on the rationale.

We would welcome contributions to Slim. Perhaps you can review the [open issues](https://github.com/ImagingDataCommons/slim/issues) and see if you can contribute.

I see you are getting help on the OHIF slack, so I'll close this issue but feel free to come back with specific questions or contributions.

**Comment by selko** [comment]
Thank you very much for the information!! 
kind regards.

**Comment by selko** [comment]
I will start with Slim then, because i am focused in digital pathology.  I saw that IDC has a branch testing Openseadragon with Slim. Is it better approach with openlayers that openseadragon?

Thank you and kind regards.

**Comment by pieper** [comment]
The Slim developers selected openlayers for a number of reasons, and it seems to be working well so we have no specific plans to switch.  The Slim API does try to encapsulate and hide openlayers so that some kind of switch could be done in the future if needed.

**Comment by selko** [comment]
Ok. But is it possible to develop over openlayers new functionalities? For example, develop a magnifier using openlayers.

**Comment by pieper** [comment]
Yes, I believe that should be very doable, but I don't have direct experience.  Maybe @hackermd or others can comment.

**Comment by hackermd** [comment]
@selko thanks for your interest in Slim. We would welcome contributions that add new functionality. Functionality that builds onto Openlayers will need to be implemented in the [dicom-microscopy-viewer](https://github.com/ImagingDataCommons/dicom-microscopy-viewer) library and fully abstracted. As @pieper pointed out, the *dicom-microscopy*viewer* is designed to fully abstract the underlying rendering library to allow switching to a different library in the future in case this may become necessary/desirable. We specifically selected Openlayers over OpenSeadragon, and would thus not be interested in switching to this library.
When considering contributing to *dicom-microscopy-viewer*, please refer to the [contribution guidelines](https://github.com/ImagingDataCommons/dicom-microscopy-viewer/blob/master/CONTRIBUTING.md) for further information.
