### ISSUE TITLE
Parametric maps of exemplary datasets 

### ISSUE THREAD

**Issue by maxfscher** [ImagingDataCommons/slim#154]
Hey, 
first of all thank you for this very nice viewer and the very good documentation. 
I have a question regarding the example datasets that you provide [here](https://imagingdatacommons.github.io/slim/). Can you share some information how the parametric maps from the Study ID **C3N-01016** were generated? Is the process somewhere described or can you provide further hints on which tool did you use? I am especially interested in how you defined the real_world_value_mappings in the parametric map dicom file. 

Thanks in advance
Max

**Comment by fedorov** [comment]
We discussed this today with @cgorman - he is the one who generated the samples you mentioned using highdicom. Chris can share the part of the code that generated those.
