### ISSUE TITLE
Bulk annotations using image coordinates do not display

### ISSUE THREAD

**Issue by CPBridge** [ImagingDataCommons/slim#163]
Microscopy Bulk Simple Annotations that are stored using AnnotationCoordinateType "2D" do not display at all in slim. They do not even appear listed under "Annotation Groups" on the right hand side.

This is observed on current master branch in both Firefox and Chrome, when communicating with a local dcm4chee instance (using the Dockerfile provided in the Slim repo). The annotation objects were created using highdicom.

**Comment by igoroctaviano** [comment]
@CPBridge @fedorov It looks like this has been fixed, correct? I think we can close this issue.

**Comment by CPBridge** [comment]
Yes!
