### ISSUE TITLE
DICOM Segmentations do not display

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/slim#169]
Together with @CPBridge, @DanielaSchacherer, @dclunie and @cgorman we  have been struggling to understand why we are unable to visualize multi-resolution DICOM SEG encoded as either TILED_SPARSE or TILED_FULL in Slim+Google DICOM Store combination. The samples are available in **tests S6 and S7** in the [IDC test inventory](https://docs.google.com/spreadsheets/d/12n1AWUynEFPatmNUphyW9IhOHaePN2jNUrzzjLunJtg/edit#gid=0) (access to the document is limited to IDC team members, but these specific samples can be shared at request with anyone interested to investigate the issue).

**Comment by igoroctaviano** [comment]
I'm getting a few 400s when using GCP:

https://healthcare.googleapis.com/v1/projects/idc-sandbox-000/locations/us/datasets/idc-dicom-test-inventory/dicomStores/test-samples/dicomWeb/studies/2.25.213661963103110408605329613498871186883/series/1.2.826.0.1.3680043.10.511.3.93656756710834591768370015932747426/instances/1.2.826.0.1.3680043.10.511.3.49566294483227479815612054298702676/frames/1683

```js
[{
  "error": {
    "code": 400,
    "message": "no PixelData found in requested instance",
    "status": "FAILED_PRECONDITION"
  }
}
]
```

There's a possibility that even though no errors were logged during the import in GCP, some segments might have silently failed. I'll retry the import in a separate dicom store to see if I get the same results.

**Comment by CPBridge** [comment]
I thought @DanielaSchacherer  had managed to access these cases successfully over DICOM web using the python client?

**Comment by igoroctaviano** [comment]
I could load the SEGs successfully locally using dcm4chee. The problem is trying to load them via GCP.

**Comment by CPBridge** [comment]
Understood, yes I thought she tried loading from GCP

**Comment by igoroctaviano** [comment]
> Hi Igor, I was indeed able to retrieve the whole instances from a Google DICOM store using the [Google DICCOMweb client](https://cloud.google.com/healthcare-api/docs/how-tos/dicomweb#dicomweb_cli) and they didn't seem corrupt or anything. What I wasn't able to do was to visualize any kind of annotation with the Slim viewer when connecting it to a Google DICOM store.
> 
> What exactly did you do when you received the error mentioned above?

Have you tried toggling the segmentation and checking the logs? I'm getting a bunch of failed requests related to missing pixel data (segments)

**Comment by fedorov** [comment]
As discussed elsewhere, this was due to missing support of BitsAllocated=1, which is now available. I confirmed this is working now, at least on the sample I tested.
