### ISSUE TITLE
code smells present in the code

### ISSUE THREAD

**Issue by AndreLuisOak** [ImagingDataCommons/slim#180]
161 code smells were found in your code, of the types
ANY - Any Type: Defining the type any for an element in the code
MUT - Missing Union Type Abstraction: When union types are not used with type aliases
LC - Large Component: Component with too many props, attributes, and/or lines of code
TP - Too Many Props: Passing too many properties to a single component
JSX - JSX outside the render method: Implementing markup in multiple methods

**Comment by igoroctaviano** [comment]
> 161 code smells were found in your code, of the types ANY - Any Type: Defining the type any for an element in the code MUT - Missing Union Type Abstraction: When union types are not used with type aliases LC - Large Component: Component with too many props, attributes, and/or lines of code TP - Too Many Props: Passing too many properties to a single component JSX - JSX outside the render method: Implementing markup in multiple methods

Hi 👋 Feel free to propose solutions in granular form (small PRs per file and type)

**Comment by igoroctaviano** [comment]
A refactoring plan is currently in progress, so I’ll close the issue for now (stale).
