### ISSUE TITLE
Investigate inability to access bulk annotations via Google Healthcare API beta

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/slim#185]
@igoroctaviano you should have the permissions - let me know otherwise!

Note the "beta" in the URL - bulk data is not supported yet in the production "v1" of GHC API.

https://healthcare.googleapis.com/beta/projects/idc-external-031/locations/us-central1/datasets/beta-test-bulk-ann/dicomStores/beta-test-bulk-ann-store/dicomWeb

I was using this instance for testing: https://andrey-slim-test.web.app/ (it is not the latest version of the code).

**Comment by igoroctaviano** [comment]
Updates:

- Study: /studies/1.3.6.1.4.1.36533.234446223213316522016052691906672206144/series/1.3.6.1.4.1.36533.1372222127159171712471486061691839611271 
- Server: https://healthcare.googleapis.com/v1beta1/projects/idc-external-002/locations/us-central1/datasets/slim_test/dicomStores/issues_data/dicomWeb

The viewer retrieves the results correctly using the new API but this dataset in particular was not loading correctly. The DimensionOrganizationType is TILED_SPARSE but PlanePositionSlideSequence was missing from both Per frame and SharedFunctionalGroupsSequence which causes parsing errors in dicom-microscopy-viewer.

Verify results:
```
Warning - Value dubious for this VR - (0x0010,0x0010) PN Patient's Name  PN [1] = <TCGA-02-0001> - Retired Person Name form
VLWholeSlideMicroscopyImage
Error - Value is zero for value 1 of attribute <Slice Thickness>
Error - Value is zero for value 1 of attribute <Imaged Volume Depth>
```

**Comment by fedorov** [comment]
Per discussion today, let's restart this experiment and create a new DICOM store with the data we know is valid. @igoroctaviano will follow up with @CPBridge to get a valid ANN sample and a corresponding SM image.

Per clarification from Vivian:

>  The DICOM store can be created at any endpoint/using any version of the API. The bulk retrieve feature is the only thing that needs to be called/envoked using the beta endpoint. Documentation can be found at: https://cloud.google.com/healthcare-api/docs/reference/rest/v1beta1/projects.locations.datasets.dicomStores.studies.series.instances.bulkdata/retrieveBulkdata

**Comment by igoroctaviano** [comment]
@fedorov 
- Test sample: https://healthcare.googleapis.com/v1beta1/projects/idc-external-031/locations/us-central1/datasets/2d_3d_point_polygon_annotation_test/dicomStores/2d_3d_point_polygon_annotation_test_store/dicomWeb
- Results:
![Screenshot 2024-01-18 at 14 45 05](https://github.com/ImagingDataCommons/slim/assets/13886933/9e7174a9-2071-45e6-a5d7-123b03ea6137)

The problem I mentioned earlier was for graphic type point. For polygons it works fine.

**Comment by fedorov** [comment]
Great news, thank you!
