### ISSUE TITLE
Clusters appear out of slide

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/slim#206]
It looks like there is a duplication/wraparound of the clusters layer

![image](https://github.com/ImagingDataCommons/slim/assets/313942/f7e8b9b7-79db-49ca-862b-8a2098700b62)

**Comment by fedorov** [comment]
@igoroctaviano is saying this is also happening for contours, but I have not seen it - need to confirm.

**Comment by igoroctaviano** [comment]
@fedorov issue addressed. https://slim-dmv.web.app/

**Comment by fedorov** [comment]
Works for me, very nice!

What was the underlying issue?

**Comment by igoroctaviano** [comment]
> Works for me, very nice!
> 
> What was the underlying issue?

I had to propagate the annotation's extent to all layers. The cluster layer needs the extent to be passed but the other layers don't.

**Comment by fedorov** [comment]
I believe this has been resolved.
