### ISSUE TITLE
Add support for Google Analytics

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/slim#51]
replaces https://github.com/herrmannlab/slim/issues/88

**Comment by fedorov** [comment]
@hackermd can this issue be prioritized? I understand this is not the most exciting feature to add, but understanding IDC usage is important for our reporting purposes and justifying continuous funding. If we are not able to report usage and justify continuous funding, we will not have funding for the implementation of the more exciting features.

**Comment by fedorov** [comment]
Yes, it is probably just those few lines - the standard code from GA. Yes, it should be maintained in the IDC fork.

**Comment by Punzo** [comment]
done in https://github.com/ImagingDataCommons/slim/pull/57

**Comment by hackermd** [comment]
Thanks @Punzo
